name: Test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  # 13:44 is an arbitrarily chosen daily time.
  - cron: '44 13 * * *'
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: test
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install
    - run: npm test
      env:
        FORCE_COLOR: 3
